apiVersion: v1
kind: Service
metadata:
  labels:
    app: serverhub
  name: serverhub-service
spec:
  type: NodePort
  ports:
  - name: port-1
    nodePort: 31812
    port: 4000
    protocol: TCP
    targetPort: 4000
  - name: port-2
    nodePort: 31514
    port: 5555
    protocol: TCP
    targetPort: 5555
  selector:
    app: serverhub